behaviors:
MonsterAgent:
trainer_type: ppo
max_steps: 500000
    hyperparameters:
batch_size: 64
      buffer_size: 2048
      learning_rate: 3.0e-4
    network_settings:
normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
extrinsic:
gamma: 0.99
        strength: 1.0
